---
name: Build and Push OR check-PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      board:
        description: "Board to Compile"
        type: choice
        required: true
        default: "M5Cardputer"
        options: ["M5Cardputer", "M5StickCPlus2", "ESP32-S3"]

jobs:
  compile_sketch:
    name: Build ${{ matrix.board.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - {
              name: "ESP32-S3 - M5Cardputer",
              env: "m5stack-cardputer",
              partitions: { bootloader_addr: "0x0000" },
            }
          - {
              name: "ESP32 - M5StickCPlus2",
              env: "m5stack-cplus2",
              partitions: { bootloader_addr: "0x1000" },
            }
          - {
              name: "Headless: ESP32-S3",
              env: "esp32-s3-devkitc-1",
              partitions: { bootloader_addr: "0x0" },
            }
          - {
              name: "CoreS3",
              env: "m5stack-cores3",
              partitions: { bootloader_addr: "0x0" },
            }
          - {
              name: "Launcher based environment: CYD",
              env: "LAUNCHER_CYD-2432S028",
              partitions: { bootloader_addr: "0x1000" },
            }
    steps:
      - uses: actions/checkout@v4

      - id: build
        name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
          key: Bruce-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: Bruce-platformio-

      - name: Restore PIO
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/.pio
          key: Bruce-pio-${{ matrix.board.env }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
                Bruce-pio-${{ matrix.board.env }}-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install platformio intelhex requests esptool

      - name: Configure Build Version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version=${{ github.ref_name }}
          else
            version="${GITHUB_SHA::7}"
          fi

          sed -i "s/-DBRUCE_VERSION=/-DBRUCE_VERSION='\"$version\"' ; /g" ./platformio.ini
          sed -i "s/-DGIT_COMMIT_HASH='\"Homebrew\"'/\!echo '-DGIT_COMMIT_HASH=\\\\\\\\\"'\$\(git describe --always --dirty)'\\\\\\\\\"'/g" ./platformio.ini

          echo "Updated platformio.ini with version: $version"
          cat ./platformio.ini

      - name: Build Firmware
        run: |
          echo "Building firmware for ${{ matrix.board.name }}"
          platformio run -e ${{ matrix.board.env }}

      - name: Build Filesystem (Optional)
        continue-on-error: true
        run: |
          echo "Building filesystem for ${{ matrix.board.name }}"
          platformio run -e ${{ matrix.board.env }} -t buildfs

      - name: Cache PIO
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/.pio
          key: Bruce-pio-${{ matrix.board.env }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Create Build Manifest
        run: |
          echo "Creating build manifest for ${{ matrix.board.name }}"
          if [ -f ".pio/build/${{ matrix.board.env }}/firmware.bin" ]; then
            cp ".pio/build/${{ matrix.board.env }}/firmware.bin" "Bruce-${{ matrix.board.env }}.bin"
          fi

          # Create a simple manifest
          echo "{\"board\": \"${{ matrix.board.name }}\", \"env\": \"${{ matrix.board.env }}\", \"built\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "Bruce-${{ matrix.board.env }}.json"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Bruce-${{ matrix.board.env }}
          path: |
            Bruce-*.bin
            Bruce-*.json
          retention-days: 7
          if-no-files-found: error

      - name: Build Summary
        run: |
          echo "✅ Successfully built ${{ matrix.board.name }}"
          echo "Environment: ${{ matrix.board.env }}"
          ls -la Bruce-* 2>/dev/null || echo "No Bruce files found"
